# Generated by Django 5.1.1 on 2024-11-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teacher_id',
            field=models.IntegerField(null=True),
        ),
    ]
