# Generated by Django 5.1.1 on 2024-11-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_section_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='essay_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('section_key', models.IntegerField(blank=True)),
                ('context', models.CharField(max_length=500)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
