# Generated by Django 5.1.1 on 2024-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_essay_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='context_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_assignment_key', models.IntegerField(blank=True)),
                ('context_question', models.CharField(blank=True, max_length=800)),
            ],
        ),
    ]
