# Generated by Django 5.1.1 on 2024-11-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_context_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context_question',
            old_name='context_question',
            new_name='context',
        ),
    ]
