# Generated by Django 5.1.1 on 2024-11-02 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_rename_context_question_context_question_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay_assignment',
            old_name='due_date',
            new_name='date_due',
        ),
        migrations.RemoveField(
            model_name='essay_assignment',
            name='context',
        ),
        migrations.AddField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 11, 2, 18, 26, 3, 590955)),
        ),
    ]
