# Generated by Django 5.1.1 on 2024-11-02 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_rename_due_date_essay_assignment_date_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 11, 2, 18, 30, 30, 384711)),
        ),
    ]
