# Generated by Django 5.1.1 on 2024-11-03 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_essay_assignment_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='essay_submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('assignment_code', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 11, 3, 15, 4, 38, 349579)),
        ),
    ]
