# Generated by Django 5.1.1 on 2024-11-03 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_essay_submitted_alter_essay_assignment_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='essay_submitted',
        ),
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 11, 3, 15, 5, 48, 353171)),
        ),
    ]
