# Generated by Django 5.1.1 on 2024-11-03 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_delete_essay_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 11, 3, 15, 7, 17, 284861)),
        ),
    ]
