# Generated by Django 5.1.1 on 2024-11-06 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_essay_assignment_assignment_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 11, 6, 15, 1, 7, 454415)),
        ),
    ]
