# Generated by Django 5.1.1 on 2024-11-10 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_alter_essay_assignment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 10, 41, 2, 76631)),
        ),
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
