# Generated by Django 5.1.1 on 2024-11-11 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_alter_essay_assignment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 17, 52, 59, 119669)),
        ),
    ]
