# Generated by Django 5.1.1 on 2024-12-29 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0035_alter_essay_assignment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 5, 45, 54, 799282)),
        ),
    ]
