# Generated by Django 5.1.1 on 2025-01-01 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0037_alter_essay_assignment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 1, 24, 8, 568704)),
        ),
    ]
