# Generated by Django 5.1.1 on 2025-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='context_understanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('sentence_number', models.IntegerField(default=0)),
                ('sentence_orig', models.CharField(blank=True, default='', max_length=4000)),
                ('messages', models.CharField(blank=True, default=0, max_length=2000)),
                ('sentence_modif', models.CharField(blank=True, default='', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='error_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('grammar', models.IntegerField(default=0)),
                ('typos', models.IntegerField(default=0)),
                ('typography', models.IntegerField(default=0)),
                ('casing', models.IntegerField(default=0)),
                ('punctuation', models.IntegerField(default=0)),
                ('spelling', models.IntegerField(default=0)),
                ('style', models.IntegerField(default=0)),
                ('redundancy', models.IntegerField(default=0)),
                ('whitespace', models.IntegerField(default=0)),
                ('misc', models.IntegerField(default=0)),
                ('confused_words', models.IntegerField(default=0)),
                ('contradiction', models.IntegerField(default=0)),
                ('wordiness', models.IntegerField(default=0)),
                ('date_time', models.IntegerField(default=0)),
                ('names', models.IntegerField(default=0)),
                ('numbers', models.IntegerField(default=0)),
                ('inconsistency', models.IntegerField(default=0)),
                ('passive_voice', models.IntegerField(default=0)),
                ('missing_words', models.IntegerField(default=0)),
                ('nonstandard_phrase', models.IntegerField(default=0)),
                ('comma', models.IntegerField(default=0)),
                ('colon_semicolon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='essay_submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('assignment_code', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('word_count', models.FloatField(default=0)),
                ('unique_word_ratio', models.FloatField(default=0)),
                ('average_word_length', models.FloatField(default=0)),
                ('noun_count', models.FloatField(default=0)),
                ('adj_count', models.FloatField(default=0)),
                ('adv_count', models.FloatField(default=0)),
                ('pronoun_count', models.FloatField(default=0)),
                ('verb_count', models.FloatField(default=0)),
                ('subordinating_clauses_count', models.FloatField(default=0)),
                ('grammar_error_count', models.FloatField(default=0)),
                ('spelling_error_count', models.FloatField(default=0)),
                ('sentiment_polarity', models.FloatField(default=0)),
                ('cohesive_device_count', models.FloatField(default=0)),
                ('readability_score', models.FloatField(default=0)),
                ('avg_sentence_length', models.FloatField(default=0)),
                ('sentence_simple', models.FloatField(default=0)),
                ('sentence_compound', models.FloatField(default=0)),
                ('sentence_complex', models.FloatField(default=0)),
                ('topic_relevance_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='langtool_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(blank=True, default=0)),
                ('message', models.CharField(blank=True, default='', max_length=1500)),
                ('shortmessage', models.CharField(blank=True, default='', max_length=1500)),
                ('replacements', models.CharField(blank=True, default='', max_length=1500)),
                ('context', models.CharField(blank=True, default='', max_length=1500)),
                ('sentence', models.CharField(blank=True, default='', max_length=1500)),
                ('final_sentence', models.CharField(blank=True, default='', max_length=1500)),
                ('sentence_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='question_composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField()),
                ('question', models.CharField(blank=True, max_length=500)),
                ('composition', models.CharField(blank=True, max_length=16000)),
                ('comment', models.CharField(default='', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='rubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(blank=True, default=0)),
                ('ideas', models.IntegerField(blank=True, default=0)),
                ('gram_punc', models.IntegerField(blank=True, default=0)),
                ('transition', models.IntegerField(blank=True, default=0)),
                ('clarity', models.IntegerField(blank=True, default=0)),
                ('word_choice', models.IntegerField(blank=True, default=0)),
                ('structure', models.IntegerField(blank=True, default=0)),
                ('lang_mechs', models.IntegerField(blank=True, default=0)),
                ('label', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vocab_recom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('word', models.CharField(blank=True, default='', max_length=200)),
                ('suggestion', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
