# Generated by Django 5.1.1 on 2024-11-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_submitted',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
