# Generated by Django 5.1.1 on 2025-01-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='difficulty_dictionary_str',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('dictionary_str', models.CharField(blank=True, default='', max_length=5000)),
            ],
        ),
    ]
