# Generated by Django 5.1.1 on 2024-11-03 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_essay_submitted_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 3, 15, 30, 32, 815722)),
        ),
    ]
