# Generated by Django 5.1.1 on 2024-11-04 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 4, 14, 51, 53, 515798)),
        ),
    ]
