# Generated by Django 5.1.1 on 2024-11-06 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(unique=True)),
                ('question', models.CharField(blank=True, max_length=500)),
                ('composition', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 6, 15, 1, 7, 459542)),
        ),
    ]
