# Generated by Django 5.1.1 on 2024-11-06 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_question_composition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='langtool_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1500)),
                ('shortmessage', models.CharField(blank=True, max_length=1500)),
                ('replacements', models.CharField(blank=True, max_length=1500)),
                ('context', models.CharField(blank=True, max_length=1500)),
                ('sentence', models.CharField(blank=True, max_length=1500)),
                ('final_sentence', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='rubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(blank=True)),
                ('ideas', models.IntegerField(blank=True)),
                ('gram_punc', models.IntegerField(blank=True)),
                ('transition', models.IntegerField(blank=True)),
                ('clarity', models.IntegerField(blank=True)),
                ('word_choice', models.IntegerField(blank=True)),
                ('structure', models.IntegerField(blank=True)),
                ('lang_mechs', models.IntegerField(blank=True)),
                ('lebel', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 6, 23, 16, 24, 890957)),
        ),
        migrations.AlterField(
            model_name='question_composition',
            name='essay_submitted',
            field=models.IntegerField(),
        ),
    ]
