# Generated by Django 5.1.1 on 2024-11-06 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_langtool_suggestion_rubrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrics',
            name='lebel',
        ),
        migrations.AddField(
            model_name='langtool_suggestion',
            name='essay_submitted',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='label',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 6, 23, 56, 35, 931134)),
        ),
        migrations.AlterField(
            model_name='langtool_suggestion',
            name='context',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='langtool_suggestion',
            name='final_sentence',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='langtool_suggestion',
            name='message',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='langtool_suggestion',
            name='replacements',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='langtool_suggestion',
            name='sentence',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='langtool_suggestion',
            name='shortmessage',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='clarity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='essay_submitted',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='gram_punc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='ideas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='lang_mechs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='structure',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='transition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='word_choice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
