# Generated by Django 5.1.1 on 2024-11-07 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_rubrics_lebel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 8, 0, 24, 3, 511764)),
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
