# Generated by Django 5.1.1 on 2024-11-09 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='langtool_suggestion',
            name='sentence_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 20, 19, 9, 27699)),
        ),
    ]
