# Generated by Django 5.1.1 on 2024-11-09 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_langtool_suggestion_sentence_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(default=0)),
                ('unique_word_ratio', models.IntegerField(default=0)),
                ('average_word_length', models.IntegerField(default=0)),
                ('noun_count', models.IntegerField(default=0)),
                ('adj_count', models.IntegerField(default=0)),
                ('adv_count', models.IntegerField(default=0)),
                ('pronoun_count', models.IntegerField(default=0)),
                ('verb_count', models.IntegerField(default=0)),
                ('subordinating_clauses_count', models.IntegerField(default=0)),
                ('grammar_error_count', models.IntegerField(default=0)),
                ('spelling_error_count', models.IntegerField(default=0)),
                ('sentiment_polarity', models.IntegerField(default=0)),
                ('cohesive_device_count', models.IntegerField(default=0)),
                ('readability_score', models.IntegerField(default=0)),
                ('avg_sentence_length', models.IntegerField(default=0)),
                ('sentence_simple', models.IntegerField(default=0)),
                ('sentece_compound', models.IntegerField(default=0)),
                ('sentence_complex', models.IntegerField(default=0)),
                ('topic_relevance_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 21, 31, 8, 215174)),
        ),
    ]
