# Generated by Django 5.1.1 on 2024-11-09 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_features_alter_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='sentece_compound',
            new_name='sentence_compound',
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 21, 45, 48, 496895)),
        ),
    ]
