# Generated by Django 5.1.1 on 2024-11-09 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_rename_sentece_compound_features_sentence_compound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='essay_submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 21, 52, 12, 652868)),
        ),
    ]
