# Generated by Django 5.1.1 on 2024-11-09 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_features_essay_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 22, 5, 8, 620628)),
        ),
        migrations.AlterField(
            model_name='features',
            name='adj_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='adv_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='average_word_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='avg_sentence_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='cohesive_device_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='grammar_error_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='noun_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='pronoun_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='readability_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='sentence_complex',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='sentence_compound',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='sentence_simple',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='sentiment_polarity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='spelling_error_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='subordinating_clauses_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='topic_relevance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='unique_word_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='verb_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='word_count',
            field=models.FloatField(default=0),
        ),
    ]
