# Generated by Django 5.1.1 on 2024-11-11 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 17, 52, 59, 121228)),
        ),
    ]
