# Generated by Django 5.1.1 on 2024-11-12 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_composition',
            name='comment',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 8, 16, 20, 362013)),
        ),
    ]
