# Generated by Django 5.1.1 on 2024-11-12 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_question_composition_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_submitted',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 8, 47, 1, 758732)),
        ),
    ]
