# Generated by Django 5.1.1 on 2024-11-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay_submitted',
            name='date_submitted',
        ),
    ]
