# Generated by Django 5.1.1 on 2024-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_remove_essay_submitted_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='vocab_recom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('word', models.CharField(blank=True, default='', max_length=200)),
                ('suggestion', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
