# Generated by Django 5.1.1 on 2024-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_vocab_recom'),
    ]

    operations = [
        migrations.CreateModel(
            name='context_undestanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('sentence_number', models.IntegerField(default=0)),
                ('sentence_orig', models.CharField(blank=True, default='', max_length=4000)),
                ('messages', models.CharField(blank=True, default=0, max_length=2000)),
                ('sentence_modif', models.CharField(blank=True, default='', max_length=4000)),
            ],
        ),
    ]
