# Generated by Django 5.1.1 on 2024-12-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_context_undestanding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='context_undestanding',
            new_name='context_understanding',
        ),
    ]
