# Generated by Django 5.1.1 on 2025-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_rename_context_undestanding_context_understanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_submitted', models.IntegerField(default=0)),
                ('grammar', models.IntegerField(default=0)),
                ('typography', models.IntegerField(default=0)),
                ('casing', models.IntegerField(default=0)),
                ('punctuation', models.IntegerField(default=0)),
                ('spelling', models.IntegerField(default=0)),
                ('style', models.IntegerField(default=0)),
                ('redundancy', models.IntegerField(default=0)),
                ('whitespace', models.IntegerField(default=0)),
                ('misc', models.IntegerField(default=0)),
                ('confused_words', models.IntegerField(default=0)),
                ('contradiction', models.IntegerField(default=0)),
                ('wordiness', models.IntegerField(default=0)),
                ('date_time', models.IntegerField(default=0)),
                ('names', models.IntegerField(default=0)),
                ('numbers', models.IntegerField(default=0)),
                ('inconsistency', models.IntegerField(default=0)),
                ('passive_voice', models.IntegerField(default=0)),
                ('missing_words', models.IntegerField(default=0)),
                ('nonstandard_phrase', models.IntegerField(default=0)),
                ('comma', models.IntegerField(default=0)),
                ('colon_semicolon', models.IntegerField(default=0)),
            ],
        ),
    ]
