# Generated by Django 5.1.1 on 2025-01-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_error_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_summary',
            name='typos',
            field=models.IntegerField(default=0),
        ),
    ]
