# Generated by Django 5.1 on 2024-08-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_essay',
            fields=[
                ('student_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('nick_name', models.TextField(default='')),
                ('age', models.IntegerField(default='')),
                ('gender', models.TextField(default='')),
                ('grade_level', models.IntegerField(default=6)),
                ('school_from', models.TextField(default='')),
                ('question1', models.TextField(default='')),
                ('answer1', models.TextField(default='')),
                ('question2', models.TextField(default='')),
                ('answer2', models.TextField(default='')),
                ('question3', models.TextField(default='')),
                ('answer3', models.TextField(default='')),
            ],
            options={
                'db_table': 'student_essay',
                'ordering': ['student_instance_id', 'first_name', 'last_name', 'nick_name', 'age', 'gender', 'grade_level', 'school_from', 'question1', 'answer1', 'question2', 'answer2', 'question3', 'answer3'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
