# Generated by Django 5.1.1 on 2024-10-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='student_essay',
            name='first_name',
            field=models.TextField(default='None'),
        ),
    ]
