# Generated by Django 5.1.1 on 2024-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_studentuser_age_remove_teacheruser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='username',
        ),
        migrations.AddField(
            model_name='customeuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
    ]
