# Generated by Django 5.1.1 on 2024-10-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_user_alter_student_essay_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
