# Generated by Django 5.1.1 on 2024-10-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_studentuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
