# Generated by Django 5.1.1 on 2024-10-04 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=80)),
                ('middlename', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('gradelevel', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('schoolname', models.CharField(max_length=250)),
                ('school_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'studentuser',
                'ordering': ['id', 'email', 'firstname', 'middlename', 'lastname', 'age', 'gender', 'gradelevel', 'schoolname', 'school_id'],
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
